version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./config/nginx/config.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 8080:8080

  backend:
    container_name: backend
    build:
      context: ./backend
    user: ${UID}:${UID}
    volumes:
      - ./backend:/app
      - ./etc/php:/usr/local/etc/php/local.conf.d/
    environment:
      # add our custom config files for the php to scan
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
    command: "php artisan serve --host=0.0.0.0 --port=8080"
  frontend:
    container_name: frontend
    image: node:latest
#    build:
#      context: ./frontend
    user: ${UID}:${UID}
    working_dir: /home/node/app
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/home/node/app
    environment:
      NODE_ENV: development
#    command: "npm run dev -- --port 8080 --host 0.0.0.0"
    command: "npm run dev -- --port 8080 --host 0.0.0.0"
    tty: true
  postgres:
    image: postgres:14.3
    container_name: postgres
#    user: ${UID}:${UID}
    environment:
      POSTGRES_DB: "larvue"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/